### ISSUE TITLE
Update ROADMAP

### ISSUE THREAD

**Issue by watilde** [watilde/chest#33]
Go major update :rocket:
---
Features I need are the floowing

Major:
- [x] Remove `chest install`, it should used `npm scripts`
- [x] Remove `chest script` it should used `npm scripts` or `npm run-script`
- [x] Remove `chest sync` temporary. I'll create new chest sync!
- [x] Also, I have to say byebye to chest.json

Patch:
- [x] Update `README.md`
- [x] Update `gh-pages`

**Comment by watilde** [comment]
Ok, let's major update.
